name: armstrong-numbers
version: 1.0.0.2

dependencies:
  - base

library:
  exposed-modules: ArmstrongNumbers
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - digits

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - armstrong-numbers
      - hspec
